travis:
  secure:
    BINSTAR_TOKEN: szBLFsVnH3uJkZ+vaXTkFMhDgCy8HvK4ubhzFjmqFIJCyhtrGV1Nr2WzeS9Zi15SYSnaHbRvA0Tfzw8dIhXd1THoGaai+vx+Av41gzzdQt7EKlHwcBKVPdC2G5bCjglzccAXAy2BNtgqVOFYCqLYkXzaiHHt3gJL9QIEmojhQ3ecI9z5ji3RLxiP9RvHLGHbvy4MjYW4y7dI8XOBseAmMWF2G2LbI1Sr0XRimsdH+YuT3tQV9tOnDfFAESW7bErJW/X06FRIx2mqbhlqYi1O0vTnrk6QP183X0a9ipl6fYMxz52BKiEF2OQF+PXuLt0of+883gXtzqRLqKALR1AotksM49DVGp1JT9JK3ZYFkv/INo7L/4+6jG3OafFQsmsocWGTtJNaFMJYwDFGUOxy/cfsz2Ij8ssbjS6+XO24MSGHZRNajx4nKthmDw4JV/8peePLCowu1o0dCer9SZmkRtKMfDdM4KUxZezcAQXI0bxomLzQeIDLKwzEAjscaS7rou37Hkus5hMADKEgff0oFkSRmB1hVDBcA38HZBoldIeFzlHdEN+OcdXSdxNp0sQqS2nZYpODsvizUeNSOpH0VpxE8aS3lFbn/ZK4NPoqRHthtma/SZ7oCwOYZd1bgwlBUiT59h+NH6OfQwqbyDyvZ4pktNqSRR9AgPhIXn70Lw8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
