travis:
  secure:
    BINSTAR_TOKEN: XxyGFf6+BZQcC13wN0P61AHZJ3A1ZtbU5n0ECqe4UhCBu2a56G2FCmI5HgWR7BtdC7KWwvgdwPrQ3oN1n1f5m6VuTZd9lB91GB+H4qOVkph/WZ0xsBenkXZT8p0GLD9LjwWMUH1dog3tMO0pY5Ov4PY3mPqL+T3kmSw7BFAyvA84fy2m9gQjeEL02G4POKCw2R5aCUzjuZRc1nysyvqSiNkxFrc903H3FX3Lf23fQLelGMTDVUyfdgSfXdKjM9rYIy3dVg2xt6j6fp4xGaC2foJXdCYchWcCisOllsOjWSgQ1poT4OPDoG0pMPFTxlQGopAOjQukhpcu7Ro7llpj3DewkhTYAxwwLvHk6keXEjnDeCdvztI85t6XpZx7YUyzrRUFH2gpD4rCt/b0DP9NWt2qg5Q9Zwyw4nS9M26K3SR7bdkBdGZhCRVZxyT2PAAE7782orbFAeM0RiOSivG4pl5K/r5eI5EQpKgebaaSwfbG4zLhlggBEFmvOGH5bLx2LW87SAKIFy4x4uhlYiygAngLmD6DfU0PumWws1ipLw4hk8mSWs9TkHFOCIVD2YBZiP3EXCp4ej9Bioxt25dv8hV3FZbYNM8yX6EkfJbioPXwXFbwjQDh93sopCCqmWpvaiA1+iKOgrniqet13upkC6o+2h9NpM/73fK7DqNpD4U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
